import { expect, it } from '../../server/node_modules/vitest/dist/index.js';
import { readFileSync } from 'node:fs';
import { VideoVisitBrowser, videoVisitListUrl, durationLabel, exitReasonLabels, observationKindLabel, type VideoVisitRow } from '../src/videoVisitBrowser';
const query = (userId='a', page=1) => ({userId,page,platform:'' as const});
const row=(id='one'):VideoVisitRow=>({id,platform:'wechat',observation_kind:'confirmed_video',entered_at:1791504000000,ended_at:1791504010000,duration_ms:10000,exit_reason:'background',complete:true,first_image_id:'image-a',last_image_id:null,received_at:'2026-10-09T00:01:00Z'});
const response=(id='one')=>({records:[row(id)],total:1,page:1,page_size:20});
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(error:Error)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
it('URL携带独立设备、平台、页码，不混聊天',()=>{const u=new URL(videoVisitListUrl({...query('a & b',2),platform:'douyin'}),'https://example.com');expect(u.pathname).toBe('/api/v1/dashboard/video-visits');expect(Object.fromEntries(u.searchParams)).toEqual({user_id:'a & b',page:'2',platform:'douyin'})});
it('未知时长不伪造零秒，保留真实零和毫秒精度',()=>{expect(durationLabel(null)).toBe('未知（记录不完整）');expect(durationLabel(0)).toBe('0 秒');expect(durationLabel(1234)).toBe('1.234 秒');expect(durationLabel(60000)).toBe('60 秒')});
it('所有离开原因有明确中文语义',()=>expect(exitReasonLabels).toEqual({page_changed:'页面变化',switched:'切换视频',exit:'退出页面',background:'切换应用或退出应用',locked:'熄屏或锁屏',interrupted:'异常中断'}));
it('选择首尾图仅限当前记录存在的引用',async()=>{const b=new VideoVisitBrowser(async()=>response());await b.load(query());b.select(row(),'first');expect(b.selected).toBeNull();b.select(b.rows[0],'last');expect(b.selected).toBeNull();b.select(b.rows[0],'first');expect(b.selected?.imageId).toBe('image-a')});
it('切设备清图，旧响应不能覆盖',async()=>{const a=deferred<ReturnType<typeof response>>(),b=new VideoVisitBrowser(q=>q.userId==='a'?a.promise:Promise.resolve(response('new')));const old=b.load(query());await b.load(query('b'));b.select(b.rows[0],'first');a.resolve(response('old'));await old;expect(b.rows[0].id).toBe('new');expect(b.userId).toBe('b');expect(b.selected?.row.id).toBe('new')});
it('筛选分页旧错误不能覆盖新响应',async()=>{const a=deferred<ReturnType<typeof response>>();let calls=0;const b=new VideoVisitBrowser(()=>++calls===1?a.promise:Promise.resolve({...response('new'),page:2}));const old=b.load(query());await b.load({...query('a',2),platform:'douyin'});a.reject(Error('old'));await old;expect(b.error).toBe('');expect(b.rows[0].id).toBe('new')});
it('注销卸载不接迟到响应，空设备不请求',async()=>{const a=deferred<ReturnType<typeof response>>();let calls=0;const b=new VideoVisitBrowser(()=>{calls++;return a.promise});await b.load(query(''));expect(calls).toBe(0);const old=b.load(query());b.invalidate();a.resolve(response());await old;expect(b.rows).toEqual([]);expect(b.loading).toBe(false)});
it('当前错误可重试且清空旧内容',async()=>{let fail=true;const b=new VideoVisitBrowser(async()=>{if(fail)throw Error('网络失败');return response()});await b.load(query());expect(b.error).toBe('网络失败');fail=false;await b.load(query());expect(b.error).toBe('');expect(b.rows.length).toBe(1)});
it('图片错误按记录和首尾引用隔离，旧设备不能污染',async()=>{const b=new VideoVisitBrowser(async()=>response());await b.load(query());const old=b.rows[0];b.imageFailed(old,'image-a');expect(b.failedImages).toContain('one:image-a');b.retryImage(old,'image-a');expect(b.failedImages).toEqual([]);await b.load(query('b'));b.imageFailed(old,'image-a');expect(b.failedImages).toEqual([])});
it('错误页码与异常响应不能显示为空记录',async()=>{const b=new VideoVisitBrowser(async()=>({...response(),page:2}));await b.load(query());expect(b.error).toContain('格式异常')});
it('生产菜单路由和真实语义接线',()=>{const read=(p:string)=>readFileSync(new URL('../src/'+p,import.meta.url),'utf8');expect(read('App.vue')).toContain("path: '/video-visits'");expect(read('main.ts')).toContain("path: '/video-visits'");expect(read('api/videoVisits.ts')).toContain('dashboardFetch');const view=read('views/VideoVisits.vue');for(const s of ['前台停留','不是播放时长','首图缺失','尾图缺失','不完整','onBeforeUnmount','browser.invalidate()','pageCaptureImageUrl','selectedImage.row'])expect(view).toContain(s);expect(view).not.toContain('删除')});

it('信息流与确认视频明确区分，未知类型不能冒称视频',()=>{expect(observationKindLabel('confirmed_video')).toBe('已确认视频');expect(observationKindLabel('unconfirmed_feed')).toBe('信息流页面停留（未确认单条视频）');expect(observationKindLabel(undefined)).toBe('观察类型未知');const view=readFileSync(new URL('../src/views/VideoVisits.vue',import.meta.url),'utf8');expect(view).toContain('视频与信息流停留');expect(view).toContain('条停留记录');expect(view).toContain('观察开始');expect(view).toContain('不是完整视频或整段应用使用时长');expect(view).toContain('observationKindLabel(row.observation_kind)');expect(view).not.toContain('记录已确认视频的一次前台停留')});
