import { readFileSync } from 'node:fs';
import { newDb } from 'pg-mem';
import type pg from 'pg';
import request from 'supertest';
import { beforeEach, describe, expect, it } from 'vitest';
import { authenticatedRequest } from '../lib/dashboardAuthTestHelper.js';
import { createApp } from '../app.js';
const uid = '00000000-0000-4000-8000-000000000001';
const path = '/api/v1/dashboard/settings/expression-delivery';
const url = `${path}?user_id=${uid}`;
let pool: pg.Pool;
beforeEach(async () => { const adapter = newDb().adapters.createPg(); pool = new adapter.Pool(); await pool.query(readFileSync(new URL('../../migrations/020_runtime_settings.sql', import.meta.url), 'utf8')); });
async function setup() { const app = createApp(pool); const dashboard = await authenticatedRequest(app); const state = await dashboard.get(url); return {app,dashboard,state}; }
describe('发送策略配置', () => {
 it('默认策略精确保留微信 GIF 专用命令、移动端同配置且要求身份',async()=>{const {app,state}=await setup(); expect(state.status).toBe(200);expect(state.body.current.revision).toBe(0);expect(state.body.current.rules).toHaveLength(4);expect(state.body.current.rules[0]).toMatchObject({packageName:'com.tencent.mm',mimeTypes:['image/gif'],versionName:'8.0.78',method:'private_command',action:'com.sogou.inputmethod.exp.commit',uriKey:'EXP_PATH_URI',requiredEditorExtras:{SUPPORT_SOGOU_EXPRESSION:1}});expect((await request(app).get('/api/v1/mobile/expression-delivery')).status).toBe(400);expect((await request(app).get('/api/v1/mobile/expression-delivery').set('X-Device-Id',uid)).body).toEqual(state.body.current);});
 it('未登录/缺CSRF/缺用户不能改全局配置',async()=>{const {app,dashboard}=await setup();expect((await request(app).put(url).send({})).status).toBe(401);expect((await dashboard.put(url).unset('X-Dashboard-Request').send({})).status).toBe(403);expect((await dashboard.get(path)).status).toBe(400);});
 it('保存、重建app持久化、旧版本冲突409、回滚产生新版本',async()=>{const {dashboard,state}=await setup();const rules=state.body.current.rules;rules[0].enabled=false;expect((await dashboard.put(url).send({expectedRevision:0,rules})).body.current.revision).toBe(1);expect((await dashboard.put(url).send({expectedRevision:0,rules:[]})).status).toBe(409);const again=await authenticatedRequest(createApp(pool));expect((await again.get(url)).body.current.rules[0].enabled).toBe(false);const rollback=await again.post(`${path}/rollback?user_id=${uid}`).send({expectedRevision:1,revision:0});expect(rollback.body.current.revision).toBe(2);expect(rollback.body.current.rules[0].enabled).toBe(true);expect(rollback.body.history.map((c:any)=>c.revision)).toEqual([1,0]);});
 it('并发保存恰好一个成功，历史最多20条',async()=>{const {dashboard,state}=await setup();const rules=state.body.current.rules;const both=await Promise.all([dashboard.put(url).send({expectedRevision:0,rules}),dashboard.put(url).send({expectedRevision:0,rules})]);expect(both.map(r=>r.status).sort()).toEqual([200,409]);for(let i=1;i<23;i++)expect((await dashboard.put(url).send({expectedRevision:i,rules})).status).toBe(200);expect((await dashboard.get(url)).body.history).toHaveLength(20);});
 it.each([{packageName:'evil.app'},{mimeTypes:['text/plain']},{method:'script'},{minVersionCode:-1},{maxVersionCode:-1},{versionName:'a'.repeat(81)},{minSdk:25},{action:'bad/action'},{uriKey:'字段'},{id:'UPPER'},{requiredEditorExtras:{key:2**31}},{requiredEditorExtras:{'bad-key':1}},{requireCompatIme:1}])('拒绝非法规则 %j 不改旧值',async patch=>{const {dashboard,state}=await setup();const rules=state.body.current.rules;Object.assign(rules[0],patch);expect((await dashboard.put(url).send({expectedRevision:0,rules})).status).toBe(400);expect((await dashboard.get(url)).body.current.revision).toBe(0);});
 it('拒绝重复ID、超量、未知字段、过大请求；允许空规则明确禁用',async()=>{const {dashboard,state}=await setup();const r=state.body.current.rules[0];for(const rules of [[r,r],Array.from({length:41},(_,i)=>({...r,id:`r${i}`})),[{...r,script:'x'}]])expect((await dashboard.put(url).send({expectedRevision:0,rules})).status).toBe(400);expect((await dashboard.put(url).send({expectedRevision:0,rules:[],padding:'x'.repeat(65536)})).status).toBe(400);expect((await dashboard.put(url).send({expectedRevision:0,rules:[]})).status).toBe(200);});
 it('保存精确范围和有符号条件且禁用规则不消失；不存在历史拒绝',async()=>{const {dashboard,state}=await setup();const rules=state.body.current.rules;Object.assign(rules[0],{minVersionCode:3180,maxVersionCode:3200,versionName:null,enabled:false,requiredEditorExtras:{A:-2147483648,B:2147483647}});const saved=await dashboard.put(url).send({expectedRevision:0,rules});expect(saved.status).toBe(200);expect(saved.body.current.rules).toEqual(rules);expect((await dashboard.post(`${path}/rollback?user_id=${uid}`).send({expectedRevision:1,revision:999})).status).toBe(400);expect((await dashboard.get(url)).body.current.revision).toBe(1);});
 it('拒绝标准交付命令字段、extras超量、版本范围倒置及非法revision',async()=>{const {dashboard,state}=await setup();const base=state.body.current.rules;for(const patch of [{method:'commit_content'},{requiredEditorExtras:Object.fromEntries(Array.from({length:9},(_,i)=>[`K${i}`,1]))},{requiredEditorExtras:{['K'.repeat(161)]:1}},{minVersionCode:10,maxVersionCode:9},{minVersionCode:Number.MAX_SAFE_INTEGER+1},{minSdk:101}]){const rules=structuredClone(base);Object.assign(rules[0],patch);expect((await dashboard.put(url).send({expectedRevision:0,rules})).status).toBe(400);}for(const expectedRevision of [-1,1.5,Number.MAX_SAFE_INTEGER+1])expect((await dashboard.put(url).send({expectedRevision,rules:base})).status).toBe(400);});

 it.each([null,'8.0.78'])('禁止微信GIF标准方式没有精确新版本：%s',async versionName=>{const {dashboard,state}=await setup();const rules=state.body.current.rules;Object.assign(rules[0],{method:'commit_content',action:null,uriKey:null,versionName});expect((await dashboard.put(url).send({expectedRevision:0,rules})).status).toBe(400);});
 it('允许指定实测新版本的微信GIF标准方式',async()=>{const {dashboard,state}=await setup();const rules=state.body.current.rules;Object.assign(rules[0],{method:'commit_content',action:null,uriKey:null,versionName:'8.0.79'});expect((await dashboard.put(url).send({expectedRevision:0,rules})).status).toBe(200);});
 it('标准默认保留API23 legacy交付，允许23而拒绝22，私有仍拒绝25',async()=>{const {dashboard,state}=await setup();const base=state.body.current.rules;expect(base.filter((r:any)=>r.method==='commit_content').map((r:any)=>r.minSdk)).toEqual([23,23,23]);const rules=structuredClone(base);rules[2].minSdk=23;expect((await dashboard.put(url).send({expectedRevision:0,rules})).status).toBe(200);rules[2].minSdk=22;expect((await dashboard.put(url).send({expectedRevision:1,rules})).status).toBe(400);rules[2].minSdk=23;rules[0].minSdk=25;expect((await dashboard.put(url).send({expectedRevision:1,rules})).status).toBe(400);});
});
